window.GameVaultCatalog = {
  "categorias": [
    {
      "id_categoría": "1.0",
      "nombre_categoría": "Acción",
      "descripción": "Juegos de ritmo rápido centrados en combate, reflejos y habilidad del jugador.",
      "id": 1,
      "nombre": "Acción",
      "descripcion": "Juegos de ritmo rápido centrados en combate, reflejos y habilidad del jugador.",
      "slug": "acci-n"
    },
    {
      "id_categoría": "2.0",
      "nombre_categoría": "Aventura",
      "descripción": "Juegos con narrativa profunda, exploración y resolución de misterios.",
      "id": 2,
      "nombre": "Aventura",
      "descripcion": "Juegos con narrativa profunda, exploración y resolución de misterios.",
      "slug": "aventura"
    },
    {
      "id_categoría": "3.0",
      "nombre_categoría": "RPG",
      "descripción": "Juegos de rol con desarrollo de personajes, historia ramificada y sistemas de progresión.",
      "id": 3,
      "nombre": "RPG",
      "descripcion": "Juegos de rol con desarrollo de personajes, historia ramificada y sistemas de progresión.",
      "slug": "rpg"
    },
    {
      "id_categoría": "4.0",
      "nombre_categoría": "Deportes",
      "descripción": "Simulaciones y arcade de disciplinas deportivas del mundo real.",
      "id": 4,
      "nombre": "Deportes",
      "descripcion": "Simulaciones y arcade de disciplinas deportivas del mundo real.",
      "slug": "deportes"
    },
    {
      "id_categoría": "5.0",
      "nombre_categoría": "Estrategia",
      "descripción": "Juegos que requieren planificación, gestión de recursos y toma de decisiones tácticas.",
      "id": 5,
      "nombre": "Estrategia",
      "descripcion": "Juegos que requieren planificación, gestión de recursos y toma de decisiones tácticas.",
      "slug": "estrategia"
    },
    {
      "id_categoría": "6.0",
      "nombre_categoría": "Terror",
      "descripción": "Juegos de horror con atmósferas perturbadoras, suspenso y supervivencia.",
      "id": 6,
      "nombre": "Terror",
      "descripcion": "Juegos de horror con atmósferas perturbadoras, suspenso y supervivencia.",
      "slug": "terror"
    },
    {
      "id_categoría": "7.0",
      "nombre_categoría": "Simulación",
      "descripción": "Juegos que replican sistemas del mundo real como ciudades, vuelos o vida cotidiana.",
      "id": 7,
      "nombre": "Simulación",
      "descripcion": "Juegos que replican sistemas del mundo real como ciudades, vuelos o vida cotidiana.",
      "slug": "simulaci-n"
    },
    {
      "id_categoría": "8.0",
      "nombre_categoría": "Peleas",
      "descripción": "Juegos de combate uno contra uno o en grupos con mecánicas de combos y habilidades.",
      "id": 8,
      "nombre": "Peleas",
      "descripcion": "Juegos de combate uno contra uno o en grupos con mecánicas de combos y habilidades.",
      "slug": "peleas"
    },
    {
      "id_categoría": "9.0",
      "nombre_categoría": "Plataformas",
      "descripción": "Juegos de desplazamiento lateral o 3D donde el jugador salta entre plataformas y obstáculos.",
      "id": 9,
      "nombre": "Plataformas",
      "descripcion": "Juegos de desplazamiento lateral o 3D donde el jugador salta entre plataformas y obstáculos.",
      "slug": "plataformas"
    },
    {
      "id_categoría": "10.0",
      "nombre_categoría": "Puzzle",
      "descripción": "Juegos basados en resolver acertijos lógicos, espaciales o creativos.",
      "id": 10,
      "nombre": "Puzzle",
      "descripcion": "Juegos basados en resolver acertijos lógicos, espaciales o creativos.",
      "slug": "puzzle"
    },
    {
      "id_categoría": "11.0",
      "nombre_categoría": "Indie",
      "descripción": "Juegos desarrollados de forma independiente, con propuestas artísticas y mecánicas únicas.",
      "id": 11,
      "nombre": "Indie",
      "descripcion": "Juegos desarrollados de forma independiente, con propuestas artísticas y mecánicas únicas.",
      "slug": "indie"
    }
  ],
  "productos": [
    {
      "id_producto": "1.0",
      "nombre": "Elden Ring",
      "descripcion": "RPG de acción en mundo abierto desarrollado por FromSoftware en colaboración con George R.R. Martin. Explora las Tierras Intermedias en una épica aventura.",
      "precio": 59.99,
      "descuento": 25.0,
      "fecha_lanzamiento": "44617.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.5",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=E3Huy2cdih0",
      "id_categoria ": "3.0",
      "id": 1,
      "slug": "elden-ring",
      "id_categoria": 3,
      "pagina": "juego-elden-ring.html"
    },
    {
      "id_producto": "2.0",
      "nombre": "The Witcher 3: Wild Hunt",
      "descripcion": "RPG de mundo abierto donde juegas como Geralt de Rivia, un cazador de monstruos en busca de su hija adoptiva en un mundo de fantasía oscura.",
      "precio": 39.99,
      "descuento": 50.0,
      "fecha_lanzamiento": "42143.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.7",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=c0i88t0Kacs",
      "id_categoria ": "3.0",
      "id": 2,
      "slug": "the-witcher-3-wild-hunt",
      "id_categoria": 3,
      "pagina": "juego.html?id=2"
    },
    {
      "id_producto": "3.0",
      "nombre": "Red Dead Redemption 2",
      "descripcion": "Épica historia del salvaje oeste americano. Juega como Arthur Morgan, forajido que lucha por sobrevivir mientras su mundo se desmorona.",
      "precio": 59.99,
      "descuento": 20.0,
      "fecha_lanzamiento": "43399.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.6",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=gmA6MrX81z4",
      "id_categoria ": "2.0",
      "id": 3,
      "slug": "red-dead-redemption-2",
      "id_categoria": 2,
      "pagina": "juego.html?id=3"
    },
    {
      "id_producto": "4.0",
      "nombre": "Hollow Knight",
      "descripcion": "Juego de acción-aventura 2D en un vasto reino de insectos subterráneo. Explora cuevas, lucha contra jefes y descubre una historia oscura.",
      "precio": 14.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "42790.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "9.3",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=UAO2urG23S4",
      "id_categoria ": "11.0",
      "id": 4,
      "slug": "hollow-knight",
      "id_categoria": 11,
      "pagina": "juego.html?id=4"
    },
    {
      "id_producto": "5.0",
      "nombre": "FIFA 24",
      "descripcion": "La entrega anual de fútbol de EA Sports con licencias oficiales, Ultimate Team mejorado, clubes mundiales y modo carrera renovado.",
      "precio": 69.99,
      "descuento": 50.0,
      "fecha_lanzamiento": "45198.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "7.2",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2195250/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=CQMFrAtxMXE",
      "id_categoria ": "4.0",
      "id": 5,
      "slug": "fifa-24",
      "id_categoria": 4,
      "pagina": "juego.html?id=5"
    },
    {
      "id_producto": "6.0",
      "nombre": "Resident Evil Village",
      "descripcion": "Continúa la historia de Ethan Winters en un misterioso pueblo europeo lleno de criaturas sobrenaturales. Terror en primera persona.",
      "precio": 39.99,
      "descuento": 25.0,
      "fecha_lanzamiento": "44323.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "8.9",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1196590/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=rHFYMiOBuSk",
      "id_categoria ": "6.0",
      "id": 6,
      "slug": "resident-evil-village",
      "id_categoria": 6,
      "pagina": "juego.html?id=6"
    },
    {
      "id_producto": "7.0",
      "nombre": "Hades",
      "descripcion": "Roguelike de acción donde juegas como Zagreus, hijo de Hades, intentando escapar del inframundo griego. Narrativa dinámica y combate fluido.",
      "precio": 24.99,
      "descuento": 20.0,
      "fecha_lanzamiento": "44091.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "9.4",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=91t0ha9x0AE",
      "id_categoria ": "11.0",
      "id": 7,
      "slug": "hades",
      "id_categoria": 11,
      "pagina": "juego-hades.html"
    },
    {
      "id_producto": "8.0",
      "nombre": "Minecraft",
      "descripcion": "Juego de construcción y supervivencia en un mundo de bloques infinito. Crea, explora y sobrevive en un universo generado proceduralmente.",
      "precio": 26.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "40865.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E10+",
      "tipo_producto": "Juego base",
      "puntuacion": "9.0",
      "imagen_url": "https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Homepage_Discover-our-games_MC-Vanilla-KeyArt_864x864.jpg",
      "video_url": "https://www.youtube.com/watch?v=MmB9b5njVbA",
      "id_categoria ": "7.0",
      "id": 8,
      "slug": "minecraft",
      "id_categoria": 7,
      "pagina": "juego.html?id=8"
    },
    {
      "id_producto": "9.0",
      "nombre": "God of War: Ragnarök",
      "descripcion": "Kratos y Atreus se embarcan en una épica aventura por los nueve reinos para evitar el Ragnarök. Acción espectacular y narrativa profunda.",
      "precio": 69.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "44874.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.5",
      "imagen_url": "https://image.api.playstation.com/vulcan/ap/rnd/202207/1117/4uH3OH4dQtHMe2gmdFuth02u.jpg",
      "video_url": "https://www.youtube.com/watch?v=7DCTM0z1S0Q",
      "id_categoria ": "1.0",
      "id": 9,
      "slug": "god-of-war-ragnar-k",
      "id_categoria": 1,
      "pagina": "juego.html?id=9"
    },
    {
      "id_producto": "10.0",
      "nombre": "Cyberpunk 2077",
      "descripcion": "RPG de mundo abierto en Night City, una megalópolis del futuro. Juega como V, un mercenario que busca la inmortalidad en las calles del mañana.",
      "precio": 59.99,
      "descuento": 50.0,
      "fecha_lanzamiento": "44175.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "8.6",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=8X2kIfS6fb8",
      "id_categoria ": "3.0",
      "id": 10,
      "slug": "cyberpunk-2077",
      "id_categoria": 3,
      "pagina": "juego.html?id=10"
    },
    {
      "id_producto": "11.0",
      "nombre": "Stardew Valley",
      "descripcion": "Juego de simulación de granja donde heredas una parcela y construyes tu vida en un pequeño pueblo. Cultiva, pesca, mina y forma relaciones.",
      "precio": 14.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "42426.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "9.5",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=8A7A1X1TVNc",
      "id_categoria ": "7.0",
      "id": 11,
      "slug": "stardew-valley",
      "id_categoria": 7,
      "pagina": "juego.html?id=11"
    },
    {
      "id_producto": "12.0",
      "nombre": "Dead by Daylight",
      "descripcion": "Juego de terror multijugador asimétrico: 4 supervivientes intentan escapar mientras un asesino los caza. Colaboración y tensión extrema.",
      "precio": 19.99,
      "descuento": 20.0,
      "fecha_lanzamiento": "42535.0",
      "disponibilidad": "En stock",
      "modo_juego": "Multijugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "7.8",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/381210/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=zng5RtWLCfQ",
      "id_categoria ": "6.0",
      "id": 12,
      "slug": "dead-by-daylight",
      "id_categoria": 6,
      "pagina": "juego.html?id=12"
    },
    {
      "id_producto": "13.0",
      "nombre": "Celeste",
      "descripcion": "Juego de plataformas narrativo sobre Madeline, quien escala la Montaña Celeste enfrentando sus propios demonios internos. Preciso y emotivo.",
      "precio": 19.99,
      "descuento": 15.0,
      "fecha_lanzamiento": "43125.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "9.2",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=70d8wnTIt34",
      "id_categoria ": "9.0",
      "id": 13,
      "slug": "celeste",
      "id_categoria": 9,
      "pagina": "juego.html?id=13"
    },
    {
      "id_producto": "14.0",
      "nombre": "Grand Theft Auto V",
      "descripcion": "Juego de mundo abierto en Los Santos. Vive las vidas de tres criminales en el crimen organizado de la ciudad. Modo historia y GTA Online.",
      "precio": 29.99,
      "descuento": 25.0,
      "fecha_lanzamiento": "41534.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "8.8",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=QkkoHAzjnUs",
      "id_categoria ": "1.0",
      "id": 14,
      "slug": "grand-theft-auto-v",
      "id_categoria": 1,
      "pagina": "juego.html?id=14"
    },
    {
      "id_producto": "15.0",
      "nombre": "Undertale",
      "descripcion": "RPG indie donde tus decisiones importan: puedes completar el juego sin matar a nadie. Personajes memorables, humor y emotividad únicos.",
      "precio": 9.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "42262.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "9.3",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/391540/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=hGHTFtrGnqk",
      "id_categoria ": "11.0",
      "id": 15,
      "slug": "undertale",
      "id_categoria": 11,
      "pagina": "juego.html?id=15"
    },
    {
      "id_producto": "16.0",
      "nombre": "Baldur's Gate 3",
      "descripcion": "RPG basado en Dungeons & Dragons. Con tus compañeros, enfrenta amenazas cósmicas en Faerûn con libertad narrativa y decisiones que cambian el mundo.",
      "precio": 59.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "45141.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.8",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=KBnDZVoSFnE",
      "id_categoria ": "3.0",
      "id": 16,
      "slug": "baldur-s-gate-3",
      "id_categoria": 3,
      "pagina": "juego-baldurs-gate-3.html"
    },
    {
      "id_producto": "17.0",
      "nombre": "Apex Legends",
      "descripcion": "Battle royale de héroes en primera persona. Elige tu leyenda, forma escuadrones de 3 y combate en arenas de alta velocidad con habilidades únicas.",
      "precio": 0.0,
      "descuento": 0.0,
      "fecha_lanzamiento": "43500.0",
      "disponibilidad": "En stock",
      "modo_juego": "Multijugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "8.4",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=innmNewjkuk",
      "id_categoria ": "1.0",
      "id": 17,
      "slug": "apex-legends",
      "id_categoria": 1,
      "pagina": "juego.html?id=17"
    },
    {
      "id_producto": "18.0",
      "nombre": "The Legend of Zelda: Tears of the Kingdom",
      "descripcion": "Aventura épica en Hyrule donde Link explora cielos, tierra y profundidades con nuevas habilidades como Ultrahand y Sinfonía para resolver puzzles.",
      "precio": 69.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "45058.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "E10+",
      "tipo_producto": "Juego base",
      "puntuacion": "9.7",
      "imagen_url": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch2/70010000096821/f20258999e8d852a496dad2961a87faf2b119488f97fb81442f378043e58b000",
      "video_url": "https://www.youtube.com/watch?v=uHGShqcAHlQ",
      "id_categoria ": "2.0",
      "id": 18,
      "slug": "the-legend-of-zelda-tears-of-the-kingdom",
      "id_categoria": 2,
      "pagina": "juego.html?id=18"
    },
    {
      "id_producto": "19.0",
      "nombre": "Mortal Kombat 1",
      "descripcion": "Reinicio del universo Mortal Kombat con Liu Kang como dios del fuego. Sistema de Kameos, Klash Kastle y nuevos fatalities brutales.",
      "precio": 69.99,
      "descuento": 20.0,
      "fecha_lanzamiento": "45188.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "8.3",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971870/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=yJO5QUNBMLU",
      "id_categoria ": "8.0",
      "id": 19,
      "slug": "mortal-kombat-1",
      "id_categoria": 8,
      "pagina": "juego.html?id=19"
    },
    {
      "id_producto": "20.0",
      "nombre": "Cities: Skylines",
      "descripcion": "Simulador de construcción y gestión de ciudades moderno. Diseña carreteras, gestiona servicios y haz crecer tu metrópolis desde cero.",
      "precio": 29.99,
      "descuento": 75.0,
      "fecha_lanzamiento": "42073.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "E",
      "tipo_producto": "Juego base",
      "puntuacion": "9.0",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/255710/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=BpWPl-OwMSw",
      "id_categoria ": "7.0",
      "id": 20,
      "slug": "cities-skylines",
      "id_categoria": 7,
      "pagina": "juego.html?id=20"
    },
    {
      "id_producto": "21.0",
      "nombre": "Sekiro: Shadows Die Twice",
      "descripcion": "Juego de acción en el Japón feudal. Juegas como un shinobi que busca rescatar a su señor y vengarse. Sistema de parrys y postura exigente.",
      "precio": 59.99,
      "descuento": 15.0,
      "fecha_lanzamiento": "43546.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.1",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/814380/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=rXMX4YJ7Lks",
      "id_categoria ": "1.0",
      "id": 21,
      "slug": "sekiro-shadows-die-twice",
      "id_categoria": 1,
      "pagina": "juego.html?id=21"
    },
    {
      "id_producto": "22.0",
      "nombre": "Portal 2",
      "descripcion": "Puzzle de ingenio con portales. Resuelve cámaras de prueba con física creativa, solo o cooperativo, con la IA antagonista GLaDOS.",
      "precio": 9.99,
      "descuento": 10.0,
      "fecha_lanzamiento": "40652.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E10+",
      "tipo_producto": "Juego base",
      "puntuacion": "9.7",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/620/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=tax4e4hBBZc",
      "id_categoria ": "10.0",
      "id": 22,
      "slug": "portal-2",
      "id_categoria": 10,
      "pagina": "juego.html?id=22"
    },
    {
      "id_producto": "23.0",
      "nombre": "Fortnite",
      "descripcion": "Battle royale free-to-play en constante evolución con colaboraciones de Marvel, Star Wars y más. Construye estructuras para sobrevivir.",
      "precio": 0.0,
      "descuento": 0.0,
      "fecha_lanzamiento": "42941.0",
      "disponibilidad": "En stock",
      "modo_juego": "Multijugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "7.9",
      "imagen_url": "https://cms-assets.unrealengine.com/cm6l5gfpm05kr07my04cqgy2x/cmmwetl8h22ka07oe7aq59gwi",
      "video_url": "https://www.youtube.com/watch?v=2gUtfBmw86Y",
      "id_categoria ": "1.0",
      "id": 23,
      "slug": "fortnite",
      "id_categoria": 1,
      "pagina": "juego.html?id=23"
    },
    {
      "id_producto": "24.0",
      "nombre": "Horizon Forbidden West",
      "descripcion": "Aloy explora una Tierra futurista infestada de máquinas. Desbloquea el misterio del Corte Rojo y salva a la humanidad con armas y herramientas.",
      "precio": 59.99,
      "descuento": 20.0,
      "fecha_lanzamiento": "44610.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "8.8",
      "imagen_url": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2420110/ss_7c1ead4b3d952fd0fb92735397945bd8732bba53.1920x1080.jpg?t=1776465869",
      "video_url": "https://www.youtube.com/watch?v=Lq594XmpPBg",
      "id_categoria ": "2.0",
      "id": 24,
      "slug": "horizon-forbidden-west",
      "id_categoria": 2,
      "pagina": "juego.html?id=24"
    },
    {
      "id_producto": "25.0",
      "nombre": "Terraria",
      "descripcion": "Juego de aventura y construcción en 2D con más de 400 enemigos, 20 jefes y cientos de objetos. Un sandbox de exploración sin límites.",
      "precio": 9.99,
      "descuento": 10.0,
      "fecha_lanzamiento": "40679.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "9.5",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=w7uOhFTrrq0",
      "id_categoria ": "2.0",
      "id": 25,
      "slug": "terraria",
      "id_categoria": 2,
      "pagina": "juego.html?id=25"
    },
    {
      "id_producto": "26.0",
      "nombre": "Civilization VI",
      "descripcion": "Juego de estrategia por turnos donde guías una civilización desde la prehistoria hasta la era espacial. Diplomacia, guerra y ciencia.",
      "precio": 59.99,
      "descuento": 75.0,
      "fecha_lanzamiento": "42664.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E10+",
      "tipo_producto": "Juego base",
      "puntuacion": "8.7",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/289070/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=5KdE0p2joJw",
      "id_categoria ": "5.0",
      "id": 26,
      "slug": "civilization-vi",
      "id_categoria": 5,
      "pagina": "juego.html?id=26"
    },
    {
      "id_producto": "27.0",
      "nombre": "Night in the Woods",
      "descripcion": "Juego de aventura narrativo sobre Mae Borowski, una felina que regresa a su pueblo natal. Explora relaciones, misterios y la vida adulta.",
      "precio": 19.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "42787.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "8.8",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/481510/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=yhGxHIcLRx0",
      "id_categoria ": "11.0",
      "id": 27,
      "slug": "night-in-the-woods",
      "id_categoria": 11,
      "pagina": "juego.html?id=27"
    },
    {
      "id_producto": "28.0",
      "nombre": "LEGO Star Wars: The Skywalker Saga",
      "descripcion": "Revive las 9 películas de Star Wars en formato LEGO. Más de 300 personajes, combate mejorado y humor clásico de la saga.",
      "precio": 59.99,
      "descuento": 25.0,
      "fecha_lanzamiento": "44656.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "E10+",
      "tipo_producto": "Juego base",
      "puntuacion": "8.5",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/920210/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=WpzeFljGRLQ",
      "id_categoria ": "2.0",
      "id": 28,
      "slug": "lego-star-wars-the-skywalker-saga",
      "id_categoria": 2,
      "pagina": "juego.html?id=28"
    },
    {
      "id_producto": "29.0",
      "nombre": "Project Zomboid",
      "descripcion": "Simulador de supervivencia zombie de mundo abierto. Sobrevive en Kentucky con gestión de recursos, enfermedades y un mundo que evoluciona.",
      "precio": 19.99,
      "descuento": 0.0,
      "fecha_lanzamiento": "41586.0",
      "disponibilidad": "En stock",
      "modo_juego": "Ambos",
      "clasificacion_edad": "M",
      "tipo_producto": "Juego base",
      "puntuacion": "9.1",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/108600/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=oVzZHplAZTg",
      "id_categoria ": "6.0",
      "id": 29,
      "slug": "project-zomboid",
      "id_categoria": 6,
      "pagina": "juego.html?id=29"
    },
    {
      "id_producto": "30.0",
      "nombre": "Hogwarts Legacy",
      "descripcion": "RPG de acción ambientado en el universo mágico de Harry Potter en el siglo XIX. Explora Hogwarts, domina hechizos y revela una conspiración antigua.",
      "precio": 59.99,
      "descuento": 15.0,
      "fecha_lanzamiento": "44967.0",
      "disponibilidad": "En stock",
      "modo_juego": "Un jugador",
      "clasificacion_edad": "T",
      "tipo_producto": "Juego base",
      "puntuacion": "8.6",
      "imagen_url": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/capsule_616x353.jpg",
      "video_url": "https://www.youtube.com/watch?v=1O6Qstncpnc",
      "id_categoria ": "3.0",
      "id": 30,
      "slug": "hogwarts-legacy",
      "id_categoria": 3,
      "pagina": "juego.html?id=30"
    }
  ]
};
